### ISSUE TITLE
Weird timestamps sent to webservice

### ISSUE THREAD

**Issue by samvermette** [leviathan/getexceptional-api-wrapper#1]
Some iOS exceptions seem to display odd dates. In some cases the "x minutes ago" even goes backward. Every time I refresh, X gets smaller. Maybe it has something to do with timezones? (mine is properly set in my account settings)

I posted this messages to the support site and Claran Lee replied with the following:

I'm guessing what has happened here is that you sent us an exception whose occurred_at timestamp was in the future (hence the x minutes ago was counting down initially). I'm not familiar with the iOS client code, but it might be worth checking whether it converts the time to UTC before it sends the error data to us.

**Comment by leviathan** [comment]
Ok, I'll look into this. I will need some days as I'm currently busy with another project.

**Comment by samvermette** [comment]
I've been watching this project and I see you pushed some really nice changes but have yet to see a fix for this issue. Any chance you'll look into it soon?

**Comment by leviathan** [comment]
I've replaced the old ISO 8601 date parse with a new one.
Can you go ahead and confirm that the new one fixes your problems:
https://github.com/leviathan/getexceptional-api-wrapper/commit/5596d87b8dfe8ff7419cf7da216049afdfe53037

**Comment by samvermette** [comment]
Nope, still getting "4h ago" http://samv.me/72W3 :(

**Comment by leviathan** [comment]
Looks like the timezone is wrong.
2008-02-01T09:00:22**+05:00** The timezone is the last part of the timestamp.

Jesus, I hoped that the new date formatter would handle it correctly.
Do you know any iOS date formatter for converting NSDate to ISO 8601 compliant format?

**Comment by samvermette** [comment]
I never used the ISO 8601 format, so I'm not sure how this can be done. Sorry :(

**Comment by samvermette** [comment]
Maybe this can help? http://developer.apple.com/library/ios/#qa/qa1480/_index.html
